<div class="articleLocationOnion"><a href='../../index.html'>首页: </a> &gt; <a href='../index_s.html'>未分类</a> &gt; JAVA异常</div><div style="color:blue" align=center>JAVA异常</div><br><div id="article_content" class="article_content tracking-ad" data-mod="popu_307" data-dsm="post">

<h1><span style="font-family:KaiTi_GB2312">异常概念：</span></h1>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">java</span><span lang="zh-CN">异常是</span><span lang="en-US">java</span><span lang="zh-CN">提供的用于处理程序中错误的一种机制。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN">所谓错误是指在程序运行的过程中发生的一些异常事件</span><span lang="en-US">(</span><span lang="zh-CN">如：除</span><span lang="en-US">0</span><span lang="zh-CN">溢出，数组下标越界，所要读取的文件不存在</span><span lang="en-US">)</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">设计良好的程序应该在异常发生时提供处理这些错误的方法，使得程序不会因为异常的发生而阻断或产生不可预见的结果。</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><br>
</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">java</span><span lang="zh-CN">程序的执行过程中如出现异常事件，可以生成一个异常类对象，该异常对象封装了异常事件的信息并将被提交给</span><span lang="en-US">java</span><span lang="zh-CN">运行时系统，这个过程称为抛出</span><span lang="en-US">(throw)</span><span lang="zh-CN">异常</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN">当</span><span lang="en-US">java</span><span lang="zh-CN">运行时系统接收到异常对象时，会寻找能处理这一异常的代码并把当前异常对象交给其处理，这一过程称为捕获</span><span lang="en-US">(catch)</span><span lang="zh-CN">异常。</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img src="11694317519075" width="450" height="250" alt=""><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<h1><span lang="zh-CN"><span style="font-family:KaiTi_GB2312">异常的分类：</span></span></h1>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img src="40564207785143" alt=""><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">E</span><span lang="en-US">rror</span><span lang="zh-CN">：称为错误，由</span><span lang="en-US">Java</span><span lang="zh-CN">虚拟机生成并抛出，包括动态链接失败，虚拟机错误等，程序对其不做处理。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">E</span><span lang="en-US">xception</span><span lang="zh-CN">：所有异常类的父类，其子类对应了各种各样可能出现的异常事件，一般需要用户显示的声明或捕获。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">R</span><span lang="en-US">untime Exception</span><span lang="zh-CN">：一类特殊的异常，如被</span><span lang="en-US">0</span><span lang="zh-CN">除，数组下标超范围等，其产生比较频繁，处理麻烦，如果显式的声明或捕获将会对程序可读性和运行效率影响很大。因此由系统自动检测并将它们交给缺省的异常处理程序（用户可不必对其处理）。</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<h1><span style="font-family:KaiTi_GB2312">异常的捕获和处理</span></h1>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">try</span><span lang="zh-CN">语句：</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">1</span><span lang="zh-CN">，</span><span lang="en-US">try{}</span><span lang="zh-CN">语句指定了一段代码，该代码就是一次捕获并处理例外的范围。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">2</span><span lang="zh-CN">，在执行过程中，该段代码可能会产生并抛出一种或几种类型的异常对象，它后面的</span><span lang="en-US">catch</span><span lang="zh-CN">语句要分别对这些异常做相应的处理</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">3</span><span lang="zh-CN">，如果没有例外产生，所有的</span><span lang="en-US">catch</span><span lang="zh-CN">代码段都被略过不执行</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">catch</span><span lang="zh-CN">语句：</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">1</span><span lang="zh-CN">，在</span><span lang="en-US">catch</span><span lang="zh-CN">语句块中是对异常进行处理的代码，每个</span><span lang="en-US">try</span><span lang="zh-CN">语句块可以伴随一个或多个</span><span lang="en-US">catch</span><span lang="zh-CN">语句，用于处理可能产生的不同类型的异常对象。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="zh-CN"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">finally</span><span lang="zh-CN">语句</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">1</span><span lang="zh-CN">，</span><span lang="en-US">finally</span><span lang="zh-CN">语句为异常处理提供一个统一的出口，使得在控制流程转到程序的其他部分以前，能够对程序的状态作统一的管理。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">2</span><span lang="zh-CN">，无论</span><span lang="en-US">try</span><span lang="zh-CN">所指定的程序块中是否抛出异常，</span><span lang="en-US">finally</span><span lang="zh-CN">所指定的代码都要被执行。</span></span></p>
<p style="margin:0in; font-size:16.0pt"><span style="font-family:KaiTi_GB2312"><span lang="en-US">3</span><span lang="zh-CN">，通常在</span><span lang="en-US">finally</span><span lang="zh-CN">语句中可以进行资源的清除工作，如：关闭打开的文件，删除临时文件等</span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<p style="margin:0in; font-size:16pt">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<img src="15075510460234" width="450" height="250" alt=""><br>
</p>
<br>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">总的来说，对于可能出现异常的代码，有两种处理办法：</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312"><br>
</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">第一、在方法中用try...catch语句捕获并处理异常，catach语句可以有多个，用来匹配多个异常。例如：</span></p>
<pre code_snippet_id="290818" snippet_file_name="blog_20140414_1_47086" name="code" class="java">public void p(int x){
 try{
  ...
 }catch(Exception e){
  ...
 }finally{
  ...
 }
}</pre><br>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">第二、对于处理不了的异常或者要转型的异常，在方法的声明处通过throws语句抛出异常。例如：</span></p>
<pre code_snippet_id="290818" snippet_file_name="blog_20140414_2_8139448" name="code" class="java">public void test1() throws MyException{
 ...
 if(....){
  throw new MyException();
 }
} </pre>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312">如果每个方法都是简单的抛出异常，那么在方法调用方法的多层嵌套调用中，Java虚拟机会从出现异常的方法代码块中往回找，直到找到处理该异常的代码块为止。然后将异常交给相应的catch语句处理。<br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img src="50868758069993" width="450" height="250" alt=""><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<h1><span style="font-family:KaiTi_GB2312">使用自定义的异常：</span></h1>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">用throws声明方法可能抛出自定义的异常，并用throw语句在适当的地方抛出自定义的异常。例如：</span></p>
<br>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<pre code_snippet_id="290818" snippet_file_name="blog_20140414_3_2185630" name="code" class="java">public class Test{
	public void regist(int num) throws MyException{
		if (num&lt;0){
			throw new MyException(&quot;人数为负值,不合理&quot;,3);
		}
		System.out.println(&quot;登记人数&quot;+num);
	}
	
	public void manager(){
			try{regist(100);}
			catch(MyException e){
					System.out.println(&quot;登记失败，出错类型码=&quot;+e.getId());
						e.printStackTrace();
				}
				System.out.print(&quot;操作结束&quot;);
				
		}
		
		public static void main(String[] args){
			Test t = new Test();
			t.manager();
			}
}
class MyException extends Exception{
	private int id;
	public MyException(String message,int id){
		super(message);
		this.id=id;
		}
		public int getId(){
			return id;
			}
	}
</pre><br>
<img src="43952816718177" alt=""><br>
<p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"></span></span></p>
<h1><span style="font-family:KaiTi_GB2312">总结：</span></h1>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;对于运行时异常，我们不要用try...catch来捕获处理，而是在程序开发调试阶段，尽量去避免这种异常，一旦发现该异常，正确的做法就会改进程序设计的代码和实现方式，修改程序中的错误，从而避免这种异常。捕获并处理运行时异常是好的解决办法，因为可以通过改进代码实现来避免该种异常的发生。</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;对于受检查异常，没说的，老老实实去按照异常处理的方法去处理，要么用try...catch捕获并解决，要么用throws抛出！</span></p>
<p style="margin:0in; font-size:16pt"><span style="font-family:KaiTi_GB2312">对于Error（运行时错误），不需要在程序中做任何处理，出现问题后，应该在程序在外的地方找问题，然后解决。</span></p>
<br>
<p style="margin:0in; font-size:16pt"><span lang="zh-CN"><span style="font-family:KaiTi_GB2312"><br>
</span></span></p>
<p style="margin:0in; font-family:宋体; font-size:16.0pt"><span lang="zh-CN"><br>
</span></p>
<p style="margin:0in; font-family:宋体; font-size:16.0pt"><span lang="zh-CN"><br>
</span></p>
   
</div><div class="ArcitleLink"><a href='http://blog.csdn.net/hejingyuan6/article/details/22413171'>原文链接</a>